version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/dns-monitor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/failover-controller"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/dns-monitor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/failover-controller"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules"
    schedule:
      interval: "monthly"
