apiVersion: v1
kind: Service
metadata:
  name: bitcoin-listener
  namespace: bitcoin
  labels:
    app.kubernetes.io/name: bitcoin-listener
    app.kubernetes.io/component: listener
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bitcoin-listener
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: metrics
      port: 9090
      targetPort: metrics
