apiVersion: v1
kind: ConfigMap
metadata:
  name: cardano-listener-config
  namespace: cardano
data:
  block-confirmations: "15"
  chain-id: "mainnet"
  topics: "blocks,transactions,events"
  output-format: "protobuf"
