apiVersion: v1
kind: ConfigMap
metadata:
  name: cardano-config
  namespace: cardano
data:
  topology.json: |
    {
      "bootstrapPeers": [
        {
          "address": "backbone.cardano.iog.io",
          "port": 3001
        },
        {
          "address": "backbone.mainnet.emurgornd.com",
          "port": 3001
        },
        {
          "address": "backbone.mainnet.cardanofoundation.org",
          "port": 3001
        }
      ],
      "localRoots": [],
      "publicRoots": [
        {
          "accessPoints": [
            {
              "address": "relays-new.cardano-mainnet.iohk.io",
              "port": 3001
            }
          ],
          "advertise": false
        }
      ],
      "useLedgerAfterSlot": 110332824
    }
