apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../cluster-envs/prod

commonLabels:
  cluster-role: listeners

# Add role+env specific patches here
# patches:
#   - path: patches/custom.yaml
