apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:IgorGerasimow/platform-design.git
              revision: HEAD
              directories:
                - path: apps/infra/*
                - path: apps/infra/observability/*
          - clusters:
              selector: {}
              values:
                env: '{{ index .metadata.labels "env" }}'
                cluster: '{{ index .metadata.labels "cluster" }}'
  template:
    metadata:
      name: '{{ .path.basename }}'
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: platform-infra
    spec:
      project: default
      source:
        repoURL: git@github.com:IgorGerasimow/platform-design.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '../../../envs/{{ .values.env }}/values/infra/{{ .path.basename }}.yaml'
          values: |
            environment: "{{ .values.env }}"
            cluster: "{{ .values.cluster }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
