apiVersion: v1
kind: ConfigMap
metadata:
  name: polygon-listener-config
  namespace: polygon
data:
  block-confirmations: "128"
  chain-id: "137"
  topics: "blocks,transactions,events"
  output-format: "protobuf"
