apiVersion: v1
kind: ConfigMap
metadata:
  name: polkadot-listener-config
  namespace: polkadot
data:
  block-confirmations: "12"
  chain-id: "polkadot"
  topics: "blocks,transactions,events"
  output-format: "protobuf"
