apiVersion: v1
kind: Service
metadata:
  name: solana-listener
  namespace: solana
  labels:
    app.kubernetes.io/name: solana-listener
    app.kubernetes.io/component: listener
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: solana-listener
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
