apiVersion: v1
kind: Service
metadata:
  name: tron-listener
  namespace: tron
  labels:
    app.kubernetes.io/name: tron-listener
    app.kubernetes.io/component: listener
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tron-listener
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
    - name: metrics
      port: 9090
      targetPort: metrics
